-- Agregar categor�as de ejemplo a la tabla Category
INSERT INTO Categories (Name)
VALUES
    ('Electrónica'),
    ('Ropa'),
    ('Hogar y Jardín'),
    ('Libros'),
    ('Juguetes'),
    ('Salud y Belleza'),
    ('Deportes y Aire Libre'),
    ('Automóviles'),
    ('Alimentos y Comestibles'),
    ('Joyería'),
    ('Muebles'),
    ('Música'),
    ('Mascotas'),
    ('Electrodomésticos'),
    ('Películas y Series de TV'),
    ('Suministros Eléctricos'),
    ('Suministros de Oficina'),
    ('Bebés y Niños'),
    ('Herramientas y Ferretería'),
    ('Fitness'),
    ('Zapatos'),
    ('Viajes'),
    ('Manualidades y Pasatiempos'),
    ('Software'),
    ('Arte y Coleccionables'),
    ('Cámaras y Fotografía'),
    ('Relojes'),
    ('Industrial y Científico'),
    ('Jardinería'),
    ('Suministros para Fiestas');
